# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465f4d9f83e9feea26092f1d0669d35a433d1e7a681c82635e57ed1513b43da84bf19897bbe948c19b129a726c492005d35467a3f49e9ac82524d0fb988e008e

test:
  secret_key_base: d67c26f63c34dbbdda8f48cdeeb79aeba3590efa849d6344489c137ebebcd6b0c8f5ed5ff5a44449663dd6999a99bf3121878575b8fbc5b0736629261ebf8c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
